name: cleaneo_user
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_otp_text_field: ^1.1.3+2
  intl_phone_number_input: ^0.7.4
  country_code_picker: ^3.0.0
  flutter_profile_picture: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.1.0
  video_player: ^2.9.1
  chewie: ^1.8.1
  table_calendar: ^3.1.2
  image_picker: ^1.0.7
  pin_code_fields: ^7.3.0
  fl_chart: ^0.68.0
  pinput: ^5.0.0
  shared_preferences: ^2.2.3
  carousel_slider: ^4.2.1
  dotted_line: ^3.2.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  dotted_border: ^2.1.0
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.6
  permission_handler: ^11.3.0
  flutter_sound: ^9.2.13
  email_auth: ^1.1.1

  package_info: ^2.0.2
  get_storage: ^2.1.1
  http: ^1.2.0
  badges: ^3.1.2
  getwidget: ^4.0.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  location: ^6.0.1
  geocoding: ^3.0.0
  intl: ^0.19.0
  provider: ^6.1.2
  fluttertoast: ^8.2.6
  device_preview: ^1.2.0
  razorpay_flutter: ^1.2.6
  lottie: ^3.1.0
  gif_view: ^0.4.3
  syncfusion_flutter_charts: ^26.1.40
  qr_code_scanner: ^1.0.1
  order_tracker: ^0.0.2
  share_plus: ^9.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  country_picker: ^2.0.26
  otp_text_field: ^1.1.3
  flutter_octicons: ^0.43.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/drawer-images/
    - assets/images/vendor Detail Images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SatoshiRegular
      fonts:
        - asset: assets/Fonts/Satoshi-Regular.otf
    - family: SatoshiLight
      fonts:
        - asset: assets/Fonts/Satoshi-Light.otf
    - family: SatoshiMedium
      fonts:
        - asset: assets/Fonts/Satoshi-Medium.otf
    - family: SatoshiBold
      fonts:
        - asset: assets/Fonts/Satoshi-Bold.otf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


